In [1]:
import numpy as np
from scipy.spatial import KDTree

x, y = np.mgrid[0:5, 2:8]
x, y

(array([[0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4]]),
 array([[2, 3, 4, 5, 6, 7],
        [2, 3, 4, 5, 6, 7],
        [2, 3, 4, 5, 6, 7],
        [2, 3, 4, 5, 6, 7],
        [2, 3, 4, 5, 6, 7]]))

In [5]:
x.ravel()

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4])

In [3]:
len(np.c_[x.ravel(), y.ravel()]), np.c_[x.ravel(), y.ravel()]

(30,
 array([[0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7]]))

In [7]:
tree = KDTree(np.c_[x.ravel(), y.ravel()])
tree

To query the nearest neighbours and return squeezed result, use

In [8]:
dd, ii = tree.query([[0, 0], [2.2, 2.9]], k=1)
print(dd, ii, sep='\n')

[2.        0.2236068]
[ 0 13]


In [9]:
dd, ii = tree.query([[0, 0]], k=1)
print(dd, ii, sep='\n')

[2.]
[0]


In [10]:
dd, ii = tree.query([[0, 0], [1,1], [2,2]], k=1)
print(dd, ii, sep='\n')

[2. 1. 0.]
[ 0  6 12]


In [11]:
dd, ii = tree.query(
    [[0, 0], [1,1], [2,2]], 
    k=1, 
    distance_upper_bound=.1,
    workers=-1
)
print(dd, ii, sep='\n')

[inf inf  0.]
[30 30 12]


In [13]:
import numpy as np
np.inf is np.inf

True

In [16]:
dd, ii = tree.query(
    [[0, 0], [1,1], [2,2]], 
    k=[5], # -- 5th nearest neighbor
    distance_upper_bound=3,
    workers=-1
)
print(dd, ii, sep='\n')

[[       inf]
 [2.23606798]
 [1.41421356]]
[[30]
 [ 1]
 [19]]


In [22]:
dd.flatten()

array([       inf, 2.23606798, 1.41421356])

In [24]:
np.array([[0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4]]).flatten()

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4])